name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - "7.2"
          - "7.3"
          - "7.4"
        dependencies:
          - "locked"
          - "highest"
        laravel:
          - "5.8.x"
          - "6.x"
          - "7.x"
        experimental:
          - false

    name: Laravel ${{ matrix.laravel }} on PHP${{ matrix.php }}-${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.laravel }}-${{ matrix.php }}-${{ matrix.os }}-${{ matrix.dependencies }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, bcmath
          coverage: none

      - name: Install Laravel Framework ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
      - name: Execute tests
        run: vendor/bin/phpunit
